/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document, as JSON */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment_methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List this account's payment methods
         * @description The method codes a create may name in `payment_methods`, with each method's fee, amount bounds and required `customer.*` fields. Read this instead of hard-coding codes — methods can be enabled or suspended without a release on your side.
         */
        get: operations["listPaymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund a card payment
         * @description Returns money on a succeeded card payment, in full (omit `amount`) or in part. QRIS and Virtual Account refunds are manual. The same optional `Idempotency-Key` contract as creating a transaction — a replayed key returns the original refund and never reaches the card processor again.
         */
        post: operations["createRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/refunds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a refund */
        get: operations["getRefund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription_customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [Beta] List customers
         * @description Closed beta. Every subscription endpoint answers 404 for accounts we have not enabled by hand, and the shape may change before general availability.
         */
        get: operations["listSubscriptionCustomers"];
        put?: never;
        /**
         * [Beta] Create or update a customer
         * @description Sending an `external_id` you have used before updates that customer instead of creating a second one, which is what makes re-running an import safe. One of `email` or `phone` is required: a customer nobody can be reached at cannot be sent a renewal reminder.
         */
        post: operations["createSubscriptionCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription_customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Beta] Retrieve a customer */
        get: operations["getSubscriptionCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * [Beta] Edit a customer
         * @description Edits the customer at this id and never creates one. Use this rather than the create endpoint when correcting an `external_id`: that one matches on `external_id`, so changing it there mints a second customer and leaves the subscriptions pointing at the first. Every field is replaced by what you send, and the same rule as creating applies — one of `email` or `phone` must survive the edit.
         */
        patch: operations["updateSubscriptionCustomer"];
        trace?: never;
    };
    "/v1/subscription_invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Beta] List invoices */
        get: operations["listSubscriptionInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription_invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Beta] Retrieve an invoice */
        get: operations["getSubscriptionInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription_plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [Beta] List live plans
         * @description Only the current version of each plan. Archived versions stay readable through the subscriptions that reference them.
         */
        get: operations["listSubscriptionPlans"];
        put?: never;
        /**
         * [Beta] Create a plan, or reprice one
         * @description Plans are immutable. Posting a `code` you have used before writes the next version and archives the one it replaces — subscribers stay on the version they signed up to until you move them, and their existing invoices keep the price they were issued at.
         *
         *     `amount` is required even when it is 0: a free plan is a real plan, so an absent field cannot be read as a free one.
         *
         *     Daily, weekly, monthly and annual. Anything longer than a year is refused.
         */
        post: operations["createSubscriptionPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Beta] List subscriptions */
        get: operations["listSubscriptions"];
        put?: never;
        /**
         * [Beta] Start a subscription
         * @description Bills the opening cycle immediately and returns with the first invoice already issued — unless the plan has a trial, which raises nothing until it ends.
         *
         *     The mode follows your key: a `kp_test_` key creates a sandbox subscription, which raises sandbox payment requests and sends no reminders to anybody.
         *
         *     Live subscriptions are for verified accounts only: until verification is through, a live key is answered `403 verification_required` and nothing is written. A sandbox key works throughout.
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [Beta] Retrieve a subscription */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Beta, test mode] Move a sandbox subscription's clock forward
         * @description Simulate the passage of time so a renewal can be watched without waiting for one.
         *
         *     This bills nothing itself. It moves the subscription's own clock; the renewal sweep then does on its next pass exactly what it does in production — issues the invoice for each cycle passed, creates the QRIS request, and extends access when it is paid. A simulation running its own billing path would be testing code nobody runs.
         *
         *     Advances accumulate, so a year of renewals can be walked one call at a time. It only moves forward: rewinding would put a subscription behind cycles it has already billed.
         *
         *     Sandbox only. A live subscription is refused `422`.
         */
        post: operations["advanceSubscriptionClock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Beta] Cancel a subscription
         * @description `at_period_end: false` (the default) stops access immediately. `at_period_end: true` honours the service already paid for and stops when the current period runs out. Neither refunds anything.
         *
         *     Cancellation is final. A payment arriving afterwards settles its invoice — the debt was real — and grants no access and restarts no billing. Cancelling an already-cancelled subscription is `409`.
         */
        post: operations["cancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Beta] Schedule a plan or quantity change
         * @description Takes effect at the next renewal, and only then. There is no immediate option: proration is not available in this release, and applying a paid upgrade before it is paid for would grant service nobody authorised.
         *
         *     The scheduled values appear as `pending_plan_id` and `pending_quantity` until the renewal applies them.
         */
        post: operations["changeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Beta] Pause a subscription
         * @description Stops billing, and stops access with it. A pause is not a free month.
         */
        post: operations["pauseSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscriptions/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Beta] Resume a paused subscription
         * @description Returns to `active`, or to `past_due` when an invoice is still outstanding — the pause did not settle the debt.
         */
        post: operations["resumeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment requests
         * @description One page of this key's payment requests, newest first, scoped to the key's mode. Malformed filters are refused 422, never silently dropped.
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * Create a payment request
         * @description Creates a payment request and, for headless integrations, attaches the
         *     rail's payload (`payment`) when it can be generated immediately. Send
         *     the buyer to `checkout_url`, or render `payment` in your own screens.
         *     A replayed `Idempotency-Key` with the identical body returns the
         *     original with status 200.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a payment request */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRefundRequest: {
            /**
             * Format: int64
             * @description Whole rupiah. Omitted means the whole remaining gross.
             */
            amount?: number;
            reason?: string;
            /** @description `payreq_<uuid>` of a succeeded card payment. */
            transaction_id: string;
        };
        CreateTransactionRequest: {
            /**
             * Format: int64
             * @description Whole rupiah. Authoritative even when order_items is sent.
             */
            amount: number;
            /** @description Everything that shapes the Kasera Pay Checkout page. Sending it, even as `{}`, is what makes this a Checkout create: the buyer walks `checkout_url` and the page collects whatever a chosen method still needs. Omitting it makes the create Direct API: `checkout_url` is still returned, but no page is assumed, so a method that needs a buyer field you did not send is refused 422 `customer_required`, and the three `is_*_required` asks are inherited from the account's payment-method settings. Sending the object replaces all three at once, so an object carrying only `steps` turns those account defaults off for this payment. */
            checkout?: {
                is_email_required?: boolean;
                is_name_required?: boolean;
                is_phone_required?: boolean;
                steps?: string[];
            };
            /** @description Who is paying — what payment rails are fulfilled with (not `payer`, which is display data). Methods may require `customer.name` etc.; read `required_customer_fields` on GET /v1/payment_methods. */
            customer?: components["schemas"]["Person"];
            description?: string;
            expires_in_minutes?: number;
            /** @description Your order id. A label — stored, echoed, filterable, never deduplicating. */
            external_id?: string;
            /** @description Your own reference. A label, like external_id. */
            merchant_ref?: string;
            /** @description Display-only detail. Σ price×quantity must equal amount or the create is refused 422 `order_items_mismatch`. */
            order_items?: components["schemas"]["OrderItem"][];
            payer?: components["schemas"]["Person"];
            /** @description Method codes this payment may be paid with, in the order a buyer should be offered them. Omitted or empty means every method enabled on the account. An unknown or disabled code is refused 422 `payment_method_unavailable`, never dropped. */
            payment_methods?: string[];
            /** @description Where the hosted checkout sends the buyer afterwards. https only on live creates; a test key also accepts http, so a store on localhost can develop the full redirect flow. */
            return_url?: string;
        };
        ErrorResponse: {
            error: {
                /** @description Stable machine-readable code, e.g. `validation_failed`. */
                code: string;
                /** @description Offending fields as dotted JSON paths of the body you sent (`customer.email`, `order_items.3.price`) mapped to the rule that failed or the offending value. */
                fields?: {
                    [key: string]: string;
                };
                /** @description English, developer-facing. */
                message: string;
                /** @description Echoes the X-Request-Id response header so you can quote the exact failed request to support. */
                request_id?: string;
            };
        };
        /** @description How-to for the buyer, in Indonesian. Print it verbatim. */
        Instructions: {
            steps: string[];
            title: string;
        };
        OrderItem: {
            name: string;
            /** Format: int64 */
            price: number;
            quantity: number;
        };
        PaymentMethod: {
            /** @example qris */
            code: string;
            display_name: string;
            fee: {
                /**
                 * Format: int64
                 * @description Flat rupiah amount.
                 */
                flat: number;
                /** @example 0,7% + Rp250 */
                label: string;
                /**
                 * Format: int64
                 * @description Percent of gross in basis points.
                 */
                percent_bps: number;
            };
            /** Format: int64 */
            max_amount: number;
            /**
             * Format: int64
             * @description Smallest amount a create on this method accepts, in whole rupiah, for this account. Each method has its own range.
             */
            min_amount: number;
            /** @description `customer.*` paths a create naming this method must send. Always an array, `[]` when the method needs nothing. */
            required_customer_fields: string[];
            /**
             * @description The `payment.type` this method's payload will carry.
             * @enum {string}
             */
            type: "qr" | "payment_code" | "redirect";
        };
        PaymentMethodList: {
            data: components["schemas"]["PaymentMethod"][];
        };
        /** @description The method-shaped payload, a discriminated union keyed on `type`. Omitted entirely until the rail has issued something for the buyer to use — never a placeholder. Only the fields belonging to the live `type` are populated. */
        PaymentPayload: {
            /** @description Short bank label, e.g. `Mandiri`. */
            bank?: string;
            /** @description Long label, e.g. `Mandiri Virtual Account` or `Credit Card`. */
            display_name?: string;
            /** @description The Virtual Account number the buyer types into their banking app (`type: payment_code`). */
            payment_code?: string;
            /** @description Raw EMV QRIS payload (`type: qr`) — encode it into a QR client-side. */
            qr_string?: string;
            /** @description Where to send the buyer (`type: redirect`). Present only while pending. */
            redirect_url?: string;
            /** @enum {string} */
            type: "qr" | "payment_code" | "redirect";
        };
        Person: {
            /** Format: email */
            email?: string;
            name?: string;
            /** @description payer.phone must be E.164; customer.phone also accepts the local Indonesian format (e.g. `08123456789`). */
            phone?: string;
        };
        Refund: {
            /** Format: int64 */
            amount: number;
            /** @description ISO-8601 at +07:00. */
            created_at: string;
            /** @example IDR */
            currency: string;
            /** @description The processor's own words when status is failed. */
            failure_reason?: string;
            /** @description `rfd_<uuid>` */
            id: string;
            livemode: boolean;
            reason?: string;
            /**
             * @description `pending` is a refund the processor never answered; it holds its amount until a human resolves it.
             * @enum {string}
             */
            status: "succeeded" | "failed" | "pending";
            /** @description `payreq_<uuid>` */
            transaction_id: string;
        };
        /** @description `status` and `paid_through` answer different questions and both matter. `status` is where the subscription sits in its lifecycle; `paid_through` is whether the customer may use the service right now. Grant access on `paid_through`: an integration that reads `status` alone cuts off every `past_due` subscriber inside the grace period they have already paid for. */
        Subscription: {
            /** Format: date-time */
            canceled_at?: string;
            /** Format: date-time */
            created_at?: string;
            /**
             * Format: date-time
             * @description When the next invoice is raised.
             */
            current_period_end?: string;
            /** Format: date-time */
            current_period_start?: string;
            /** @description `cust_<uuid>` */
            customer_id?: string;
            /**
             * Format: date-time
             * @description A cancellation already scheduled for the period end.
             */
            ends_at?: string;
            external_id?: string;
            /** @description `sub_<uuid>` */
            id?: string;
            /** @description Which mode this subscription belongs to. Always present, `false` included — a missing field would have to be read as live. */
            is_test?: boolean;
            /**
             * Format: date-time
             * @description Service access lapses at this instant. Absent until something has been paid for.
             */
            paid_through?: string;
            /** @description A change waiting for the next renewal. This is what the next invoice will use. */
            pending_plan_id?: string;
            pending_quantity?: number;
            /** @description `plan_<uuid>` */
            plan_id?: string;
            quantity?: number;
            /** @enum {string} */
            status?: "trialing" | "active" | "past_due" | "paused" | "canceled";
            /**
             * Format: date-time
             * @description Where this sandbox subscription's clock stands, when it has been advanced. Absent on live subscriptions, which have no clock to move.
             */
            test_clock?: string;
            /** Format: date-time */
            trial_ends_at?: string;
        };
        SubscriptionCustomer: {
            /** Format: date-time */
            created_at?: string;
            email?: string;
            external_id?: string;
            /** @description `cust_<uuid>` */
            id?: string;
            name?: string;
            phone?: string;
        };
        /** @description One billing cycle's bill. It carries what the customer owes and nothing about Kasera's fee — that is on the transaction named by `payment_request_id`, which you can fetch from `GET /v1/transactions/{id}`. */
        SubscriptionInvoice: {
            /**
             * Format: int64
             * @description Still owed. This is the figure to show a payer.
             */
            amount_due?: number;
            /** Format: date-time */
            created_at?: string;
            /** @example IDR */
            currency?: string;
            /** @description `cust_<uuid>` */
            customer_id?: string;
            /** Format: int64 */
            discount?: number;
            /**
             * Format: date-time
             * @description When payment is expected. Not the payment attempt's expiry — a QRIS code lives an hour and the invoice link outlives it.
             */
            due_at?: string;
            /** @description `inv_<uuid>` */
            id?: string;
            /** @description Human-facing */
            number?: string;
            /** Format: date-time */
            paid_at?: string;
            /** @description Recorded by the merchant rather than collected by Kasera. Settled, but not Kasera-processed volume — keep the two apart in reporting. */
            paid_externally?: boolean;
            /** @description `payreq_<uuid>` — the live collection attempt, absent when there is none. */
            payment_request_id?: string;
            /** Format: date-time */
            period_end?: string;
            /** Format: date-time */
            period_start?: string;
            /** Format: int64 */
            setup?: number;
            /**
             * @description `void` withdraws the debt; `uncollectible` admits it is still owed and no longer being chased.
             * @enum {string}
             */
            status?: "open" | "paid" | "void" | "uncollectible";
            /** @description `sub_<uuid>` */
            subscription_id?: string;
            /** Format: int64 */
            subtotal?: number;
            /** Format: int64 */
            tax?: number;
            /** Format: int64 */
            total?: number;
        };
        SubscriptionPlan: {
            /** Format: int64 */
            amount?: number;
            /** @description A superseded version. Still readable; no new subscription may start on it. */
            archived?: boolean;
            code?: string;
            /** Format: date-time */
            created_at?: string;
            /** @example IDR */
            currency?: string;
            /** Format: int64 */
            discount_amount?: number;
            /** @description `plan_<uuid>` */
            id?: string;
            interval_count?: number;
            /** @enum {string} */
            interval_unit?: "day" | "week" | "month" | "year";
            name?: string;
            /** Format: int64 */
            setup_amount?: number;
            trial_days?: number;
            /** @description Which version of `code` this is. An invoice records the version it was billed on, so a repriced plan never restates an old bill. */
            version?: number;
        };
        Transaction: {
            /**
             * Format: int64
             * @description Gross, whole rupiah. `amount = fee + net`, always.
             */
            amount: number;
            /** @description The hosted Kasera Pay Checkout page for this payment. */
            checkout_url: string;
            /** @description ISO-8601 at +07:00. */
            created_at: string;
            /** @example IDR */
            currency: string;
            customer?: components["schemas"]["Person"];
            description: string;
            /** @description ISO-8601 at +07:00. */
            expires_at: string;
            external_id?: string;
            /** Format: int64 */
            fee: number;
            /** @description `payreq_<uuid>` */
            id: string;
            instructions: components["schemas"]["Instructions"];
            /** @description false on objects a test key created — no real money moves. */
            livemode: boolean;
            merchant_ref?: string;
            /** Format: int64 */
            net: number;
            order_items?: components["schemas"]["OrderItem"][];
            /** @description ISO-8601 at +07:00, null until paid. */
            paid_at: string | null;
            payer?: components["schemas"]["Person"];
            payment?: components["schemas"]["PaymentPayload"];
            /** @description Lowercase code of the method this payment was created for — read off the row, not today's catalogue. */
            payment_method: string;
            return_url?: string;
            /** @description Which channel created this request. Always `api` here; history read back may also say `merchant`, `payment_page` or `unknown`. */
            source: string;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "expired" | "canceled";
        };
        TransactionList: {
            data: components["schemas"]["Transaction"][];
            /** @description More rows behind this page — pass the last id as starting_after. */
            has_more: boolean;
        };
        /** @description The `payment.paid` delivery POSTed to your webhook endpoint. Verify `Kasera-Signature-V1` (`t=<unix>,v1=<hex>`; each `v1` is lowercase hex HMAC-SHA256 over `<unix>.<raw body>` with your endpoint's signing secret; reject if `t` is older than five minutes; accept if any `v1` matches, since two are sent during a secret-rotation grace). The legacy body-only `Kasera-Signature` header is still sent but deprecated. Dedupe on `id` (also sent as the `Kasera-Event-Id` header). Delivery is at-least-once. */
        WebhookEvent: {
            /** @description ISO-8601 at +07:00. */
            created_at: string;
            data: {
                /** Format: int64 */
                amount: number;
                /** @example IDR */
                currency: string;
                customer?: components["schemas"]["Person"];
                external_id?: string;
                merchant_ref?: string;
                /** @description ISO-8601 at +07:00. */
                paid_at: string | null;
                /** @description `payreq_<uuid>` */
                payment_request_id: string;
            };
            /** @description `evt_<uuid>` — dedupe on this. */
            id: string;
            livemode: boolean;
            /** @enum {string} */
            type: "payment.paid";
        };
        /** @description The dashboard's test delivery — proof that signing and connectivity work, carrying nothing that looks like money. Signed and headed exactly like a real event. */
        WebhookTestPing: {
            /** @description ISO-8601 at +07:00. */
            created_at: string;
            /** @description `evt_<uuid>` */
            id: string;
            livemode: boolean;
            /** @description Always true. */
            test: boolean;
            /** @enum {string} */
            type: "test.ping";
        };
    };
    responses: {
        /** @description `internal` — something went wrong on our side. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `not_found` — no such object in this key's mode. A live key cannot see test objects nor a test key live ones. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `rate_limited` — over 300 requests/minute on this key. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `already_canceled` or `invalid_state` — the request was well formed and would have been legal a moment ago. A retried cancel lands here, which is why it is not a 422. */
        SubscriptionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `unauthorized` — missing/malformed Authorization header or an invalid/revoked API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `invalid_request` — the body is malformed or a field is unusable. `error.message` names what to fix. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Optional, at most 255 characters of valid UTF-8. The only thing that deduplicates a create: a replay with the identical body returns the original object (status 200), a replay with a different body is refused 409. No key means every attempt is its own object. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.0 document describing this API. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalogue. Not paged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    createRefund: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional, at most 255 characters of valid UTF-8. The only thing that deduplicates a create: a replay with the identical body returns the original object (status 200), a replay with a different body is refused 409. No key means every attempt is its own object. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRefundRequest"];
            };
        };
        responses: {
            /** @description The refund as it stands once the processor answered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            /** @description `invalid_idempotency_key`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `not_refundable` or `idempotency_conflict`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `validation_failed`, `refund_not_supported` or `refund_exceeds_amount`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
            /** @description `refund_refused` — nothing was refunded, safe to retry — or `refund_unresolved` — the amount is held pending and must NOT be retried; contact support. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `rfd_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The refund. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listSubscriptionCustomers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This account's customers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SubscriptionCustomer"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    createSubscriptionCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    /** @description They asked not to be emailed. Email is opt-out where WhatsApp is opt-in. */
                    email_opted_out?: boolean;
                    /** @description Your own identifier. Matching on it is what makes a re-import an update. */
                    external_id?: string;
                    name: string;
                    phone?: string;
                    /** @description They agreed to be messaged on WhatsApp. Without it no WhatsApp reminder is ever scheduled for them. */
                    whatsapp_opted_in?: boolean;
                };
            };
        };
        responses: {
            /** @description The customer. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionCustomer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getSubscriptionCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `cust_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionCustomer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    updateSubscriptionCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `cust_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    email_opted_out?: boolean;
                    /** @description Unique among your customers. 422 if another of yours already holds it. */
                    external_id?: string;
                    name: string;
                    phone?: string;
                    whatsapp_opted_in?: boolean;
                };
            };
        };
        responses: {
            /** @description The customer as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionCustomer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listSubscriptionInvoices: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This account's invoices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SubscriptionInvoice"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getSubscriptionInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `inv_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invoice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionInvoice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listSubscriptionPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The plans a new subscription may start on. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SubscriptionPlan"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    createSubscriptionPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Whole rupiah per cycle. 0 is a free plan.
                     */
                    amount: number;
                    /** @description Stable across versions; what ties a plan's history together. */
                    code: string;
                    /**
                     * Format: int64
                     * @description A flat reduction per cycle. Cannot exceed `amount`.
                     */
                    discount_amount?: number;
                    /** @default 1 */
                    interval_count?: number;
                    /** @enum {string} */
                    interval_unit: "day" | "week" | "month" | "year";
                    name: string;
                    /**
                     * Format: int64
                     * @description Charged once, on the first invoice only.
                     */
                    setup_amount?: number;
                    /** @description A trial raises no invoice at all. Access runs to the trial's end and the first bill is issued when it expires. */
                    trial_days?: number;
                };
            };
        };
        responses: {
            /** @description The new plan version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPlan"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This account's subscriptions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Subscription"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description `cust_<uuid>` */
                    customer_id: string;
                    external_id?: string;
                    /** @description `plan_<uuid>` */
                    plan_id: string;
                    /** @default 1 */
                    quantity?: number;
                    /**
                     * Format: date-time
                     * @description RFC3339. The day the first cycle opens, and the calendar day every later cycle anchors to. Defaults to today.
                     */
                    start_at?: string;
                };
            };
        };
        responses: {
            /** @description The subscription. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `verification_required` — live subscriptions need a verified account; use a sandbox key meanwhile. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    advanceSubscriptionClock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date-time
                     * @description RFC3339. Where the subscription's clock should stand after this call — later than where it stands now, which the `test_clock` field reports.
                     */
                    to: string;
                };
            };
        };
        responses: {
            /** @description The subscription, with its clock moved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    at_period_end?: boolean;
                };
            };
        };
        responses: {
            /** @description The subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SubscriptionConflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    changeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description `plan_<uuid>` */
                    plan_id?: string;
                    quantity?: number;
                };
            };
        };
        responses: {
            /** @description The subscription, with the change pending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    pauseSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SubscriptionConflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    resumeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `sub_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["SubscriptionConflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description Page size, 1–100. Out of range falls back to 20. */
                limit?: number;
                /** @description The last `id` of the previous page (`payreq_<uuid>`). A cursor that does not name one of your payment requests is refused 422 `invalid_cursor`. */
                starting_after?: string;
                status?: "pending" | "succeeded" | "failed" | "expired" | "canceled";
                external_id?: string;
                merchant_ref?: string;
                /** @description RFC3339 timestamp, e.g. `2026-08-18T09:00:00+07:00`. */
                created_after?: string;
                /** @description RFC3339 timestamp. */
                created_before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `invalid_filter` or `invalid_cursor`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional, at most 255 characters of valid UTF-8. The only thing that deduplicates a create: a replay with the identical body returns the original object (status 200), a replay with a different body is refused 409. No key means every attempt is its own object. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay — the original payment request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description `invalid_idempotency_key` — the header is over 255 characters or not valid UTF-8. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `merchant_suspended` — this account is suspended. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `idempotency_conflict` — this Idempotency-Key was already used with a different request body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `body_too_large` — request body over 1 MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `validation_failed`, `invalid_body`, `order_items_mismatch`, `payment_method_unavailable`, `customer_required`, `amount_too_small`, `amount_too_large`, `expiry_too_long` or `expiry_too_short` — `error.fields` names the offending fields as dotted JSON paths. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `rate_limited`, `unverified_count_cap` or `unverified_amount_cap`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `payreq_<uuid>` */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["Internal"];
        };
    };
}
